[build]
  base = "frontend"
  publish = "build"  # Replace with your actual build directory
  command = "npm run build"  # Replace with your actual build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200